#This is where I add all curated mappings
connection:

# Applied to every table unless overridden on that table row.
defaults:
  catalog: "Elevate"
  schema: "landing"
  lakehouse_write: "curated"
  write_mode: "overwrite"
  write_schema_option: "overwriteSchema"
  extract:
    select_behavior: "individual columns"
    column_names: []
    select_creation_statement: ""
    filter_expression: null
    except_column: ""
    column_partition_name: null
    batch_size: 50000
